- models.py
> Renamed import from napalm_base to napalm

- source/flask_app.py
This PR is to cover off class selection as discussed in https://github.com/afourmy/eNMS/issues/53.
> Select prod or debug class based on environment variable - Issue #53

- README.md
- docs/base/installation.rst
> Revert "A few  minor adjustments to the container docs"

- eNMS/automation/routes.py
> #126 [BUG] ERROR: invalid input syntax for integer: 'DatabaseBackupService

- eNMS/services/data_validation/netmiko_validation.py
- requirements.txt
Add use_genie support in the netmiko_validation service
> Initial support for netmiko use_genie

- docs/automation/workflows.rst
Had some user questions yesterday on set_var/get_var and wanted to push these doc changes to make it easier to grasp.
> Clarifying for User

- eNMS/models/execution.py
This puts the status first and re-adds the "run by" information.
> Minor email notification 'subject' change

- eNMS/forms/automation.py
- eNMS/templates/forms/service_form.html
Users confusing "Waiting time" for service with Netmiko "Timeout". This to make it clearer.
> Pretty Name Update

- docs/advanced/rest_api.rst
- eNMS/framework/rest.py
- eNMS/models/inventory.py
Not sure if I just re-submitted....messing around with git, if you see two pull, only check latest.
> CustomSearch API enpoint

- docs/advanced/administration.rst
- eNMS/framework/cli.py
Added new comment to allow the deletion of old changelog entries.
Also added relevant documentation with examples.
> added new command line argument to delete changelogs

- docs/automation/services.rst
- docs/base/installation.rst
- eNMS/models/automation.py
Per discussion and feedback from Antoine:
1. this allows access to app.send_email()
2. added a minor documentation clarification for LDAP users
> Add the 'app' to the available variables, minor doc update

- eNMS/server.py
Hi Antoine - if you wanted the change discussed earlier, I wanted to make sure that I sent it to you.  Thanks!
> Add db.session.commit into catch_exceptions decorator for REST API

- eNMS/controller/administration.py
- eNMS/forms/administration.py
- eNMS/models/administration.py
- eNMS/server.py
- setup/settings.json
- added session timeout to be configured via settings.json, user will be logged out after X minutes of inactivity.
- fixed issue with the results log deletion not deleting because of foreign key dependency.
> added session timeout and fixed issue with result log deletion

- eNMS/models/automation.py
These were some options for potential indexes to add based on the slow_query_log_file analysis
> Potential indexes to add

- eNMS/static/js/workflow.js
This can help reduce display issues for a workflow with a large number of services in the Workflow Builder.
> Workflow graph - updating nodes and edges less frequently

- eNMS/controller/inventory.py
- gunicorn.py
This PR addresses the issues we encountered in our CentOS 7 environment.
The two main issues were:
1. Parameter passing to tmux
2. TERM environment variable not set for tmux
> changes to WebSSH multiplexing to work in different environment

- eNMS/services/miscellaneous/ansible_playbook.py
- eNMS/templates/forms/service.html
- eNMS/templates/help/ansible/arguments.html
- eNMS/templates/help/ansible/options.html
- eNMS/templates/help/common/device_query.html
- eNMS/templates/help/common/iteration_devices.html
- eNMS/templates/help/common/iteration_values.html
- eNMS/templates/help/common/postprocessing.html
- eNMS/templates/help/common/preprocessing.html
- eNMS/templates/help/common/skip_query.html
Context sensitive help for service and ansible_playbook
> Added links for service and ansible_paybook context sensitive help

- eNMS/server.py
I changed the execution order so a disabled plugin would not cause the module to be loaded.
Added exception handler so eNMS won't crash because of issues with a plugin.
> corrected issues where plugin could prevent eNMS from starting

- docs/automation/services.rst
- eNMS/templates/forms/service.html
- eNMS/templates/help/custom/impacting.html
- setup/properties.json
Trying to add help for custom properties - minor change to the service.html template.
> Custom properties - context sensitive help

- eNMS/services/data_validation/netmiko_prompts.py
Replace the current device password with ******** in the command list and app log.
> netmiko_prompts: Prevent password log to app log

- eNMS/services/workflow/python_snippet.py
- eNMS/templates/help/python_snippet/source_code.html
Adding context sensitive help to the most commonly used service...we should have done this long time ago.
> python_snippet context sensitive help

- eNMS/services/miscellaneous/rest_call.py
> Add security logging to rest_call.py

- eNMS/server.py
This is the change that I made that seemed to help - maybe this is easier to read than email.
(was unsure if other changes might also be desired).
> Proposed fix target pool/devices for Tasks and /rest/run_service

- docs/automation/services.rst
- eNMS/models/automation.py
- eNMS/templates/forms/service.html
- eNMS/templates/help/common/notification_header.html
Trying new Draft pull request feature
> Draft: Notification header variable substitution fix

- eNMS/services/miscellaneous/git.py
Order of operations changed so git service can handle uncommitted changes in local repository
PULL - COMMIT - PUSH --> COMMIT - PULL - PUSH
> Changed order of operations
