eNMS-automation/eNMS

Dockerfile

Update Dockerfile to apply execute perms using chmod.
Uses RUN instead of just editing perms of boot.sh for
idempotence.
- Add line to Dockerfile which runs 'chmod +x' on the Entrypoint.
Resolves:
'docker: Error response from daemon: OCI runtime create failed:
container_linux.go:348: starting container process caused "exec:
"./boot.sh": permission denied": unknown.'

Apply execute perms to Entrypoint via Dockerfile

---

config.py
eNMS/__init__.py
gunicorn.py

Added optional environment variables to eNMS and Gunicorn per issue #117
Tested with the following commands on linux.
``` bash
export ENMS_LOG_LEVEL='CRITICAL'
export GUNICORN_LOG_LEVEL='critical'
export GUNICORN_ACCESS_LOG='None'
./boot.sh 
```

added optional environment variables for logging for gunicorn and enms

---

eNMS/admin/routes.py

eNMS does not support when the user is not found in database. No verification is done when object "user" is "None".

[BUG] crash when user not found in base

---

eNMS/models/execution.py
eNMS/services/workflow/payload_extraction.py
eNMS/services/workflow/payload_validation.py

set_retries() can be called during post-processing on any service to update the number of remaining retries.  Setting retries to zero stops all subsequent retries.

Add set_retries() in post-processing

---

docs/_static/custom.css

Expanding width for computer screen browsers - related to https://github.com/readthedocs/sphinx_rtd_theme/issues/117 plus another stackoverflow article that also icnluded a .wy-nav-content width rule (originally: 1500px; changed to 100% here).
This should, for larger screens, allow more of the screen width to be utilized per comments from Aaron earlier today.  I had an uglier fix prior to this but was able to clean it up to this with a tiny bit of experimentation.

Adding custom CSS override to the RTD theme

---

eNMS/controller/administration.py
eNMS/forms/administration.py
eNMS/static/base.js
eNMS/templates/forms/database_migration_form.html

This was tested via the UI and the REST API.
If the new argument, skip_update_pools_after_import, is not provided, then the migrate_import behavior still does change a little bit.  The pools are updated at the end of the migrate_import function - unless this parameter is set to False (and if True, the update is skipped).

Option to skip updating the pools after the migrate_import.

---

eNMS/static/js/table.js

Issue: 
- in the Run result filtering, a change to the selected value in the "bool" search column (e.g., "Success" in a Result display) is not automatically applied.
Workaround:
- There is an existing work-around - you can push the Refresh button.
Proposed solution:
- Substituting the 'change' event handler seems to address this minor behavior

table filter - bool column - event handler => change 

---

eNMS/forms/__init__.py
eNMS/forms/automation.py
eNMS/models/automation.py
eNMS/services/data_validation/netmiko_prompts.py
eNMS/services/data_validation/netmiko_validation.py

Added a Jumpserver group to netmiko_validation and netmiko_prompts that accepts parameters for how to jump from the target device to a remote.  When use_jumpserver is false, no behavior is affected.

Added jumpserver support to netmiko validation and prompts

---

eNMS/models/automation.py

Disable echo verification (cmd_verify), which on by default in Netmiko 3 to prevent timeouts on previously working services.

Disable netmiko 3's cmd_verify for all netmiko connections

---

docs/advanced/administration.rst
docs/advanced/configuration_management.rst
docs/advanced/rest_api.rst
docs/advanced/search_system.rst
docs/automation/default_services.rst
docs/automation/scheduling.rst
docs/automation/services.rst
docs/automation/workflows.rst
docs/base/features.rst
docs/base/installation.rst
docs/base/release_notes.rst
docs/inventory/network_visualization.rst
docs/inventory/pools.rst
docs/inventory/web_connection.rst

Updates to documentation.  In some cases heading markers have been extended beyond the current text.  It's valid for the heading markers to be longer than the heading text, but not shorter.  This simplifies our auto-docs-updates that change the length of some headings.

Documentation updates

---

eNMS/services/data_validation/netmiko_prompts.py

Terminate wait for output when the confirmation text is seen or on timeout.  The previous implementation always waited for the timeout.
Previously working service started failing with an exception EOFError/bad file descriptor.  I suspect netmiko v3 changed the timeout behavior for send_command_timing.  This implementation runs faster for the sunny day scenario and also handles timeouts.

netmiko_prompts: Detect confirmation string in output

---

eNMS/services/data_validation/netmiko_prompts.py
eNMS/services/data_validation/netmiko_validation.py

Remove any \U0000's from Netmiko's session_log that gets returned on a timeout.  Netmiko includes a \U0000 for every time it checks the socket for more data from the remote system.

Delete unicode nulls returned in the session_log after a timeout

---

eNMS/static/css/main.css

Two visual improvemets.
1. Enable CodeMirror vertical resizing.
2. Prevent text area resizing in horizontal direction to preserver layout.

prevent textarea resize horizontally, added codemirror resize

---

eNMS/server.py

pages defined in plugin settings were not available in RBAC for access management

added logic to make pages available in RBAC

---

eNMS/templates/forms/service.html

I liked the set label for removing the duplicated code.
In recent testing, the custom properties for non-boolean types were not showing their labels.
I think the {% set label %} needs to be moved to be before that {% if values["type"] == "boolean" %}.

Moved {% set label %} to be just before the {% if values["type"] == "boolean" %}

---

eNMS/models/automation.py

The following code produces: TypeError: payload_helper() got multiple values for argument 'device'
set_var("x", 1, "device", "section")
get_var("x", "device", "section")

Fix get_var issue with positional parameters

---

eNMS/services/file_transfer/generic_file_transfer.py

A GET file transfer failed because the service checked for existence of the source as a local file.

generic_file_transfer:  Limit source exists check to puts

---

docs/advanced/custom_properties.rst
docs/automation/custom_device_properties.rst
docs/automation/custom_link_properties.rst
docs/automation/services.rst
docs/base/installation.rst
eNMS/controller/base.py
eNMS/database.py
eNMS/models/automation.py
gunicorn.py

1. gunicorn.py - added a post_fork() that calls db.engine.dispose() if preload_app
2. eNMS/controller/base.py - added `atexit` method to call db.engine.dispose()
3. eNMS/models/automation.py - bug fix to log method in enter_remote_device
4. docs/automation/installation.rst - added information on WatchedFileHandler for logging.json and fixed any build warnings.
5. docs/automation/services.rst - in Variables section, added separate Device and Link custom properties files.

db.engine.dispose() for preload_app, atexit; enter_remote_device log fix, minor doc change(s)

---

eNMS/static/js/table.js

When testing earlier changes, the periodic table refresh did not seem to work.
In the code, below, 'run' is being passed in as `tableId`, but the selector for the table appeared to be `"#table-run"`

Minor refreshTable selector adjustment

---

eNMS/server.py

Added query parameter config_name to /rest/configuration.  Config_name specifies which device config property to return.  The default is "configuration" which provides backward compatible behavior.

Allow retrieval of all device config fields

---

eNMS/services/configuration/netmiko_configuration.py

Config mode is always being entered into, even when the box is unchecked. Adding this line will allow users to decide if they do not want to enter config mode.

Minor fix to honor config_mode in the service.

---

eNMS/static/js/workflowBuilder.js

Allow HTML in the iteration label in the Workflow Builder

workflowBuilder.js: restored iteration hover after change in vis.js

---

eNMS/controller.py
eNMS/static/js/base.js
eNMS/static/js/workflowBuilder.js

The workflow_stop endpoint now checks the current user against the runtime's creator by default, with an optional override. 
This new functionality is implemented in `workflowBuilder.js` using the added `showConfirmationPanel()` function in `base.js`, which opens a simple jsPanel prompting the user to continue if they truly intend to stop another user's workflow.

Confirmation Panel & workflow_stop modifications

---

eNMS/static/js/base.js

Discovered that the confirmation panel `openPanel()` call was resulting in "403 - Operation not allowed" errors from user accounts. Added `checkRbac: false` to bypass the search for endpoint/form access that doesn't exist.

Confirmation panel RBAC bugfix
